# Generated by Django 3.1.6 on 2021-02-14 01:53

from django.db import migrations, models
import django.utils.timezone
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210213_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(default=django.utils.timezone.now, upload_to='images/', verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='image_ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
