# Generated by Django 3.1.6 on 2021-02-14 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210213_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='owner_id',
        ),
        migrations.AlterField(
            model_name='image',
            name='hash_con',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='image',
            name='hash_div',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
