# Generated by Django 3.1.6 on 2021-02-14 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210213_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
