# Generated by Django 3.1.6 on 2021-02-14 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210213_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='timestamp',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
