# Generated by Django 3.1.6 on 2021-02-14 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210213_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='timestamp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
