# Generated by Django 3.1.6 on 2021-02-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210213_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='hash',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
